//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnalTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelOrder
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public int RequiredRooms { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
