//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnalTravel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KarnalTravelEntities : DbContext
    {
        public KarnalTravelEntities()
            : base("name=KarnalTravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelOrder> HotelOrders { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<RestaurantsOrder> RestaurantsOrders { get; set; }
        public virtual DbSet<TouristSpotOrder> TouristSpotOrders { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Resturant> Resturants { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<TouristSpot> TouristSpots { get; set; }
        public virtual DbSet<Resorts_> Resorts_ { get; set; }
        public virtual DbSet<ResturantImage> ResturantImages { get; set; }
        public virtual DbSet<ToristspotImage> ToristspotImages { get; set; }
        public virtual DbSet<HotelImage> HotelImages { get; set; }
        public virtual DbSet<ResortImage> ResortImages { get; set; }
        public virtual DbSet<TransportImage> TransportImages { get; set; }
        public virtual DbSet<Transportion> Transportions { get; set; }
    }
}
