//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnalTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResturantImage
    {
        public int id { get; set; }
        public string imgUrl { get; set; }
        public Nullable<int> resturantId { get; set; }
    
        public virtual Resturant Resturant { get; set; }
    }
}
